version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: shop-api-pg
    restart: unless-stopped
    ports:
      - "5439:5432"
    environment:
      POSTGRES_USER: shop
      POSTGRES_PASSWORD: shop
      POSTGRES_DB: shop
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
